:sectnums:
== Dokumentation E-Mail

Als politisches Bündnis sind wir sowohl intern als auch in der Außenwirkung und Vernetzung auf eine stabile, zuverlässige Kommunikation angewiesen.
E-Mail ist dabei ein zentraler Bestandteil.
Wir möchten auch bei der Mail darauf achten, dass die Kontrolle nicht nur in einer Hand liegt und das System anpassbar ist.

=== Ausgangssituation

Bisher hat Steffi alleine die E-Mail-Verteiler des Buntnis verwaltet.
Der Nachteil hier ist, dass wir als Buntnis die Liste der Einträge auf den Verteilern kaum administrieren können.
Änderungen, Neuzugänge und Abgänge müssen so immer über die eine zuständige Person laufen.

Wir möchten eine neue Lösung etablieren, bei der folgende Bedingungen erfüllt sind:

* Die Administration der Liste (Ändern/Hinzufügen/Entfernen) soll einfach möglich sein
Die Optimallösung wäre hier, ein Rollensystem zu haben, bei dem nur ein kleiner Kreis volle Kontrolle hat, ein erweiterter Kreis aber Ergänzungen machen kann.
* Es soll die Möglichkeit geben, dass sich ggf. jeder auf eine externe Liste eintragen kann.
So könnte eine Art Newsletter geschaffen werden.
* Ist die hauptverantwortliche Person nicht mehr zuständig, soll die geschaffene Infrastruktur einfach umgezogen werden können.
Die Dokumentation soll so vollständig sein, dass das System jederzeit 1:1 übernommen werden kann.

Durch das Reservieren der Buntnis-Domains `buntnis-ilmenau.de` und `buntnis.de` wurde es uns außerdem möglich, die Mail-Verteiler-Adressen mit der Buntnis-Domain zu versehen.

=== Konzeption des neuen Systems

Benötigt werden drei Adressen:

. Info (info@buntnis-ilmenau.de)
. Intern (intern@buntnis-ilmenau.de)
. Extern (news@buntnis-ilmenau.de)

Diese haben unterschiedliche Anforderungen, wer an sie senden kann und an wen sie weiterleiten.

==== Info

Jeder -> `info@buntnis-ilmenau.de` -> Liste[ausgewählte Buntnis-Mitglieder]

Die Info-Adresse ist die Adresse, über die man von Außen das Buntnis kontaktieren kann.
Sie empfängt daher von beliebigen Mailadressen Mails und leitet diese an die Buntnis-Mitglieder weiter, die aktiv die Mails ans Buntnis erhalten wollen.
Das Versenden von der Info-Adresse soll auch möglich sein.
Dazu sind SMTP-Daten notwendig, die derzeit nur an einen kleinen Personenkreis ausgegeben werden sollen.

==== Intern

Liste[Alle Mitglieder] -> `intern@buntnis-ilmenau.de` -> Liste[Alle Mitglieder]

Die interne Adresse ist die Möglichkeit, dass Buntnis-Mitglieder alle anderen Buntnis-Mitglieder erreichen können.
So sind Sender- und Empfänger-Liste hier identisch.

==== Extern

Liste[ausgewählte Buntnis-Mitglieder] -> `news@buntnis-ilmenau.de` -> Liste[jeder Interessierte]

Die externe Adresse ist die Adresse, die jeder Interessierte abonnieren kann.
Da diese Interessierten eine Mail von der offiziellen `buntnis-ilmenau.de`-Domain erhalten, sollte auch hier gut ausgewählt werden, wer das Recht erhält, über diese Adresse zu versenden.
Insgesamt sollte auf dieser Adresse Disziplin herrschen, sodass pro Monat maximal 2-3 Mails vom Buntnis gesendet werden.
Alles andere ist unnötige Belastung für die Abonnenten des Buntnis.

=== Technische Komponenten

Die Domain nimmt alle Mails entgegen, die an eine `@buntnis-ilmenau.de`- oder `@buntnis.de`-Adresse gerichtet sind.
Über einen sogenannten `MX-Record` wird gesteuert, wohin diese Mails weitergeleitet werden.

An dieser Stelle kann ein SMTP-Relay-Service eingebunden werden, der die Nachrichten entgegennimmt und nach bestimmten Regeln weiterleitet.

Wir verwenden Amazon SES (Simple E-Mail Service).
Dieses ist ein äußerst günstiger und skalierbarer SMTP-Service.
Im Gegensatz zu anderen Services ermöglicht es uns zu einem sehr geringen Preis beliebig viele Mails weiterzuleiten, während es alle Steuerungsmöglichkeiten bietet (von wo, nach wo usw.)
Das inkludiert auch ein Dashboard zur Übericht über Mail-Verkehr und fehlgeschlagene Mail-Versuche, sowie hohe Sicherheitsstandards zur Verifikation von Absendern.

=== Anleitung zum Aufsetzen des Mail-Systems

https://docs.aws.amazon.com/de_de/ses/latest/dg/sending-email-list-management.html

. Login in AWS (https://aws.amazon.com/de/) und Auswahl von SES
. Erste Einrichtung wählen & Mail-Adresse `tech@buntnis-ilmenau.de` angeben
. Buntnis-Domain hinzufügen
. Mail verifizieren
. DKIM (DomainKeys Identified Mail)-Prozess starten (`Sendedomäne verifizieren`)
** Sendedomäne verifizieren -> kopieren der benötigten DNS-Records
** Beim Domain-Provider DNS-Konfiguration anpassen:
** CNAME-Records entsprechend Angaben von Amazon hinzufügen
. ggf. kann der Virtual Deliverability Manager angeschaltet werden.
Er bietet ein Dashboard mit zusätzlichen Informationen, wie Klickraten und anderen Statistiken.
. Abschließend muss noch eine Authentifizierung bei Amazon durchgeführt werden.
Hier reicht eine kurze Beschreibung der geplanten Maßnahmen.

====
Als Demokratiebündnis benötigen wir den Mail-Service, um sowohl unsere internen Mail-Verteiler zu realisieren, als auch externen Interessierten einen Newsletter bereitstellen zu können.
====

==== List- & Subscription-Management

siehe https://docs.aws.amazon.com/ses/latest/dg/sending-email-list-management.html

SES hat ein eingebautes Listenmanagement.
Dieses kann Mailing-Listen, sogenannte `Kontaktlisten` verwalten, in der die Kontakte stehen, die auf ein Thema abonniert haben.
Daran angeschlossen ist auch ein Subscription Management, das beispielsweise automatische Unsubscribe-Links an versendete Mails anhängt.

Dazu müssen wir nun in die AWS-CLI oder ein SDK der Wahl wechseln.

IMPORTANT: In der EU ist das Empfangen von Mails mit Amazon SES nicht möglich.
Ich muss doch weiter suchen-.-
