name: Buntnis-Deployment Prod

on:
  push:
    branches:
      - "production"

jobs:
  build:
    name: Bauen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - name: Abhängigkeiten laden
        run: npm ci
      - name: Projekt bauen
        run: npm run build
      - name: Dokumentation bauen
        run: npm run generate-docs
      - uses: actions/upload-artifact@master
        with:
          name: result
          path: dist/

  deploy:
    name: Deployen
    runs-on: ubuntu-latest
    steps:
      - name: Vorbereiten
        uses: actions/checkout@v4

      - name: Hole gebautes Ergebnis
        uses: actions/download-artifact@master
        with:
          name: result
          path: dist/

      - name: FTP-Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: buntnis-ilmenau.de
          username: buntnis-ad
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/buntnis-ilmenau-de/
          server-dir: httpdocs/
    needs: [build]
